### ISSUE TITLE
SortedArray handles incomparable values poorly

### ISSUE THREAD

**Issue by kriskowal** [montagejs/collections#27]
If multiple, incomparable values are added to a sorted array, and subsequently removed, the sorted array should behave effectively like a plain array with push and pop. As yet, the search functions are returning indeterminate values and adding removing values from seemingly random positions.

See: https://github.com/montagejs/frb/pull/13

**Comment by simon-weber** [comment]
One problem I see is that callers of `search` that deal in equality (eg `searchFirst/Last`) make assumptions about the equality of elements around the result index. But, `search` only guarantees that the index is somewhere in streak of one or more incomparable values.

I think the fix is to adjust `searchFirst/Last` to scan both left and right from `search`'s index, then scan within that range for their final result.
